-- MySQL Script generated by MySQL Workbench
-- Fri Dec 27 14:45:25 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema learn
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema learn
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `learn` DEFAULT CHARACTER SET utf8 ;
USE `learn` ;

-- -----------------------------------------------------
-- Table `learn`.`uporabnik`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `learn`.`uporabnik` (
  `upime` VARCHAR(255) NOT NULL,
  `geslo` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `ime` VARCHAR(50) NOT NULL,
  `priimek` VARCHAR(50) NOT NULL,
  `vkey` VARCHAR(255) NULL,
  `vkeyStatus` TINYINT NULL,
  PRIMARY KEY (`upime`),
  UNIQUE INDEX `upime_UNIQUE` (`upime` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `learn`.`kategorija`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `learn`.`kategorija` (
  `imekategorije` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`imekategorije`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `learn`.`ucilnica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `learn`.`ucilnica` (
  `imeucilnice` VARCHAR(255) NOT NULL,
  `vrsta_ucilnice` VARCHAR(15) NOT NULL,
  `kljuc` VARCHAR(50) NULL,
  `opis_ucilnice` VARCHAR(255) NULL,
  `kategorija_imekategorije` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`imeucilnice`, `kategorija_imekategorije`),
  INDEX `fk_ucilnica_kategorija1_idx` (`kategorija_imekategorije` ASC),
  CONSTRAINT `fk_ucilnica_kategorija1`
    FOREIGN KEY (`kategorija_imekategorije`)
    REFERENCES `learn`.`kategorija` (`imekategorije`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `learn`.`test`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `learn`.`test` (
  `idtest` INT NULL AUTO_INCREMENT,
  `ucilnica_imeucilnice` VARCHAR(255) NOT NULL,
  `ime_testa` VARCHAR(255) NOT NULL,
  `trajanje` INT NOT NULL,
  `st_vprasanj` INT NOT NULL,
  `vidnen` ENUM('DA', 'NE') NOT NULL,
  PRIMARY KEY (`idtest`, `ucilnica_imeucilnice`),
  INDEX `fk_test_ucilnica1_idx` (`ucilnica_imeucilnice` ASC),
  CONSTRAINT `fk_test_ucilnica1`
    FOREIGN KEY (`ucilnica_imeucilnice`)
    REFERENCES `learn`.`ucilnica` (`imeucilnice`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `learn`.`vprasanja`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `learn`.`vprasanja` (
  `idvprasanja` INT NULL AUTO_INCREMENT,
  `test_idtest` INT NOT NULL,
  `vprasanje` VARCHAR(255) NOT NULL,
  `tocke` INT NOT NULL,
  `slika` BLOB NULL,
  PRIMARY KEY (`idvprasanja`, `test_idtest`),
  INDEX `fk_vprasanja_test1_idx` (`test_idtest` ASC),
  CONSTRAINT `fk_vprasanja_test1`
    FOREIGN KEY (`test_idtest`)
    REFERENCES `learn`.`test` (`idtest`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `learn`.`odgovori`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `learn`.`odgovori` (
  `idodgovori` INT NULL AUTO_INCREMENT,
  `odgovor` VARCHAR(255) NOT NULL,
  `pravilen` TINYINT NOT NULL,
  `vprasanja_idvprasanja` INT NOT NULL,
  `vprasanja_test_idtest` INT NOT NULL,
  PRIMARY KEY (`idodgovori`, `vprasanja_idvprasanja`, `vprasanja_test_idtest`),
  INDEX `fk_odgovori_vprasanja1_idx` (`vprasanja_idvprasanja` ASC, `vprasanja_test_idtest` ASC),
  CONSTRAINT `fk_odgovori_vprasanja1`
    FOREIGN KEY (`vprasanja_idvprasanja` , `vprasanja_test_idtest`)
    REFERENCES `learn`.`vprasanja` (`idvprasanja` , `test_idtest`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `learn`.`vclanjen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `learn`.`vclanjen` (
  `ucilnica_imeucilnice` VARCHAR(255) NOT NULL,
  `uporabnik_upime` VARCHAR(255) NOT NULL,
  `vrsta_clanstva` ENUM('admin', 'user') NOT NULL,
  PRIMARY KEY (`ucilnica_imeucilnice`, `uporabnik_upime`),
  INDEX `fk_ucilnica_has_uporabnik_uporabnik1_idx` (`uporabnik_upime` ASC),
  INDEX `fk_ucilnica_has_uporabnik_ucilnica_idx` (`ucilnica_imeucilnice` ASC),
  CONSTRAINT `fk_ucilnica_has_uporabnik_ucilnica`
    FOREIGN KEY (`ucilnica_imeucilnice`)
    REFERENCES `learn`.`ucilnica` (`imeucilnice`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ucilnica_has_uporabnik_uporabnik1`
    FOREIGN KEY (`uporabnik_upime`)
    REFERENCES `learn`.`uporabnik` (`upime`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `learn`.`ucilnica_has_test`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `learn`.`ucilnica_has_test` (
  `ucilnica_imeucilnice` VARCHAR(255) NOT NULL,
  `test_idtest` INT NOT NULL,
  PRIMARY KEY (`ucilnica_imeucilnice`, `test_idtest`),
  INDEX `fk_ucilnica_has_test_test1_idx` (`test_idtest` ASC),
  INDEX `fk_ucilnica_has_test_ucilnica1_idx` (`ucilnica_imeucilnice` ASC),
  CONSTRAINT `fk_ucilnica_has_test_ucilnica1`
    FOREIGN KEY (`ucilnica_imeucilnice`)
    REFERENCES `learn`.`ucilnica` (`imeucilnice`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ucilnica_has_test_test1`
    FOREIGN KEY (`test_idtest`)
    REFERENCES `learn`.`test` (`idtest`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `learn`.`resuje`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `learn`.`resuje` (
  `test_idtest` INT NULL AUTO_INCREMENT,
  `uporabnik_upime` VARCHAR(255) NOT NULL,
  `zacetek` DATETIME NOT NULL,
  `rezultat` INT NOT NULL,
  PRIMARY KEY (`test_idtest`, `uporabnik_upime`),
  INDEX `fk_test_has_uporabnik_uporabnik1_idx` (`uporabnik_upime` ASC),
  INDEX `fk_test_has_uporabnik_test1_idx` (`test_idtest` ASC),
  CONSTRAINT `fk_test_has_uporabnik_test1`
    FOREIGN KEY (`test_idtest`)
    REFERENCES `learn`.`test` (`idtest`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_test_has_uporabnik_uporabnik1`
    FOREIGN KEY (`uporabnik_upime`)
    REFERENCES `learn`.`uporabnik` (`upime`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `learn`.`sklop`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `learn`.`sklop` (
  `idsklop` INT NULL AUTO_INCREMENT,
  `ucilnica_imeucilnice` VARCHAR(255) NOT NULL,
  `opis` VARCHAR(255) NULL,
  PRIMARY KEY (`idsklop`, `ucilnica_imeucilnice`),
  INDEX `fk_vsebina_ucilnica1_idx` (`ucilnica_imeucilnice` ASC),
  CONSTRAINT `fk_vsebina_ucilnica1`
    FOREIGN KEY (`ucilnica_imeucilnice`)
    REFERENCES `learn`.`ucilnica` (`imeucilnice`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `learn`.`vsebina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `learn`.`vsebina` (
  `idvsebine` INT NULL AUTO_INCREMENT,
  `sklop_idsklop` INT NOT NULL,
  `sklop_ucilnica_imeucilnice` VARCHAR(255) NOT NULL,
  `vrsta` VARCHAR(50) NOT NULL,
  `besedilo` VARCHAR(255) NULL,
  `datoteka` BLOB NULL,
  PRIMARY KEY (`idvsebine`, `sklop_idsklop`, `sklop_ucilnica_imeucilnice`),
  INDEX `fk_datoteke_sklop1_idx` (`sklop_idsklop` ASC, `sklop_ucilnica_imeucilnice` ASC),
  CONSTRAINT `fk_datoteke_sklop1`
    FOREIGN KEY (`sklop_idsklop` , `sklop_ucilnica_imeucilnice`)
    REFERENCES `learn`.`sklop` (`idsklop` , `ucilnica_imeucilnice`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
