USE learn;
INSERT INTO kategorija VALUES('Programiranje');
INSERT INTO kategorija VALUES('Poslovanje');
INSERT INTO kategorija VALUES('Finance');
INSERT INTO kategorija VALUES('Pisarniška produktivnost');
INSERT INTO kategorija VALUES('Osebnostini razvoj');
INSERT INTO kategorija VALUES('Grafično oblikovanje');
INSERT INTO kategorija VALUES('Življenski slog');
INSERT INTO kategorija VALUES('Fotografija');
INSERT INTO kategorija VALUES('Zdravje in vadba');
INSERT INTO kategorija VALUES('Glasba');
INSERT INTO kategorija VALUES('Učenje');